spring:
  application:
    name: billing-service

  rabbitmq:
    host: localhost
    port: 5672
    username: ${KOINOVIO_RABBITMQ_USERNAME}
    password: ${KOINOVIO_RABBITMQ_PASSWORD}

  data:
    mongodb:
      host: localhost
      port: 27017
      database: koinovio-billing

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false



server:
  port: 8081